robot_radius: 0.75

robot_base_frame: base_footprint
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 10.0

resolution: 0.05

obstacle_range: 2.5
raytrace_range: 3.0

origin_x: -10.0
origin_y: -10.0
width: 800.0
height: 800.0

#layer definitions
static1:
    map_topic: /occupancy_grid
    subscribe_to_updates: false
    static_map: true
    use_maximum: false

static2:
    map_topic: /occupancy_grid_depth
    subscribe_to_updates: false
    static_map: true
    use_maximum: true
   
inflation:
    inflation_radius: 2.5 # 3.0
    # cost_scaling_factor: 1.75

obstacles_layer:
    enabled: true
    observation_sources: pointcloud
    pointcloud: {sensor_frame: base_footprint, data_type: PointCloud2, topic: /ransac_cloud, marking: true, clearing: true}
    # pointcloud: {sensor_frame: base_footprint, data_type: PointCloud2, topic: /laser_cloud_move_base, marking: true, clearing: true}
    #laser: {sensor_frame: hokuyo_main, data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true}
    #depth: {sensor_frame: camera_optical_frame, data_type: PointCloud2, topic: /oakd_camera/depth/points, marking: true, clearing: true}

