global_frame: map
rolling_window: true
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 2.0
transform_tolerance: 2.0
static_map: false

map_topic: /occupancy_grid

plugins:
  - {name: static,                    type: "costmap_2d::StaticLayer"} 
#  - {name: obstacles_layer,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
